ARG BUILDER_IMAGE="docker.io/golang:1.20.5-bookwork@sha256:3164c26b2e170b18e2325aa0554699e7bb19a658333601659c04838855897f7a"
ARG COMPRESSOR_BASE_IMAGE="docker.io/alpoine:3.18.2@sha256:25fad2a32ad1f6f510e528448ae1ec69a28ef81916a004d3629874104f8a7f70"

FROM ${BUILDER_IMAGE} AS builder
WORKDIR /project
COPY \
 --chmod=777 \
 . .
RUN scripts/build.sh

FROM ${COMPRESSOR_BASE_IMAGE} AS compressor
ARG UPX_INSTALLATION_COMMAND="apk add \
    libgcc=12.2.1_git20220924-r10 \
    libstdc++=12.2.1_git20220924-r10 \
    upx=4.0.2-r0 \
  && rm -rf /var/cache/apt/*"
RUN eval "${UPX_INSTALLATION_COMMAND}"
WORKDIR /project
COPY \
  --from=builder \
  --chmod=777 \
  /project/app ./
RUN upx --brute app

FROM scratch AS runner
COPY \
  --from=builder \
  --chmod=444 \
  /project/config.yml ./
COPY \
  --from=compressor \
  --chmod=111 \
  /project/app ./

ENTRYPOINT [ "./app" ]